app:
  build: .
  command: bin/rails server --binding=0.0.0.0 --port=3000
  volumes:
    - .:/app
  volumes_from:
    - box
  ports:
    - "3000:3000"
  extra_hosts:
    - "db:192.168.192.32"
    #- "db:${LOCAL_DB_HOST}"
box:
  image: busybox
  volumes:
    - /box
