development: &development
    storage:       :s3
    bucket:        "development"
    s3_host_name:  "s3"
    url:           ":s3_alias_url"
    path:          ":class/:attachment/:id_partition/:style/:filename"
    s3_host_alias: "s3:10001/development"
    s3_region:    "eu-west-1"

test: *development

production: &production
    storage: :s3
    #bucket:  <%= ENV["S3_BUCKET_NAME"] %>
    url:     ":s3_domain_url"
    path:    ":class/:attachment/:id_partition/:style/:filename"
    s3_storage_class: :reduced_redundancy

staging: *production
